name = "sleme"

main = "build/worker/shim.mjs"
compatibility_date = "2022-08-13"

[build]
command = "worker-build --release"

[env.dev]
workers_dev = true
vars = { ENV = "dev" }

[env.prod]
name = "sleme"
routes = [
    { pattern = "sleme.salzian.dev", custom_domain = true }
]
vars = { ENV = "prod" }
