name: CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**/package.json'
      - '**/yarn.lock'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**/package.json'
      - '**/yarn.lock'
    types:
      # default events
      - opened
      - synchronize
      - reopened

      # Run CI when PR is undrafted. Otherwise, another push is required.
      - ready_for_review
  release:
    types:
      - released
  repository_dispatch: # Needed for Cloudflare Deploy button

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      working-directory: ./bot

  # TODO Add deploy stage

  deploy:
    runs-on: ubuntu-latest
    # Only run the CD on releases
    if: github.event_name == 'release' && github.event.action == 'released'
    environment: prod
    needs:
      - build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: yarn install --frozen-lockfile

      - name: Setup cargo cache
        id: cache-cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ./target
          key: cargo-${{ runner.os }}-${{ github.ref_name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-${{ github.ref_name }}-
            cargo-${{ runner.os }}-main-
            cargo-${{ runner.os }}-prod-
            cargo-${{ runner.os }}-

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-${{ github.sha }}
          path: ./build

      - run: yarn run deploy:prod
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
