name: CI/CD

on:
  push:
    branches:
      - main

    paths-ignore:
      - '**.md'
      - '**/package.json'
      - '**/yarn.lock'

  pull_request:
    branches:
      - main

    paths-ignore:
      - '**.md'
      - '**/package.json'
      - '**/yarn.lock'

    types:
      # default events
      - opened
      - synchronize
      - reopened

  release:
    types:
      - released

  repository_dispatch: # Needed for Cloudflare Deploy button

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

jobs:
  build-bot:
    uses: ./.github/workflows/workflow-worker-build.yml
    with:
      application-name: bot
      working-directory: ./bot

  deploy-bot:
    uses: ./.github/workflows/workflow-worker-deploy.yml
    needs:
      - build-bot
    with:
      application-name: bot
      working-directory: ./bot
