name: CI/CD

on:
  push:
    branches:
      - main

    paths-ignore:
      - '**.md'
      - '**/package.json'
      - '**/yarn.lock'

  pull_request:
    branches:
      - main

    paths-ignore:
      - '**.md'
      - '**/package.json'
      - '**/yarn.lock'

  release:
    types:
      - released

  repository_dispatch: # Needed for Cloudflare Deploy button

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

jobs:
  build-bot:
    uses: ./.github/workflows/workflow-worker-build.yml
    with:
      application-name: bot
      working-directory: ./bot

  deploy-bot:
    uses: ./.github/workflows/workflow-worker-deploy.yml
    if: github.event_name == 'release' && github.event.action == 'released'
    needs:
      - build-bot
    with:
      application-name: bot
      working-directory: ./bot

  deploy-bot-dry-run:
    uses: ./.github/workflows/workflow-worker-deploy-dry-run.yml
    if: github.event_name != 'release'
    needs:
      - build-bot
    with:
      application-name: bot
      working-directory: ./bot
