name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - "prod"
      - "*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiKey: ${{ secrets.CF_API_KEY }}
          email: ${{ secrets.CF_EMAIL }}
          wranglerVersion: "2.0.25"
          environment: "prod"
