on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      application-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup cargo cache
        id: cache-cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ./target
          key: cargo-${{ runner.os }}-${{ github.ref_name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-${{ github.ref_name }}-
            cargo-${{ runner.os }}-main-
            cargo-${{ runner.os }}-

      - name: Setup rust toolchain
        if: steps.cache-cargo.outputs.cache-hit != 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          default: true
          profile: minimal

      - name: Install worker-build
        if: steps.cache-cargo.outputs.cache-hit != 'true'
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: install
          args: --bins worker-build

      - name: Build worker
        working-directory: ${{ inputs.working-directory }}
        run: worker-build --release

      - name: Upload build artifacts
        # TODO if: github.event_name == 'release'
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ github.sha }}-${{ inputs.application-name }}
          path: ./{{ inputs.working-directory }}/build