on:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only run the CD on releases
    # TODO if: github.event_name == 'release' && github.event.action == 'released'
    # TODO environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: yarn install --frozen-lockfile

      - name: Setup cargo cache
        id: cache-cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ./target
          key: cargo-${{ runner.os }}-${{ github.ref_name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-${{ github.ref_name }}-
            cargo-${{ runner.os }}-main-
            cargo-${{ runner.os }}-

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-${{ github.sha }}-${{ inputs.application-name }}
          path: ./build

      # TODO - run: yarn run deploy:prod
      # TODO   env:
      # TODO     CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      # TODO     CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
