on:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string

jobs:
  deploy:
    name: "[DRY-RUN] Deploy ${{ inputs.application-name }}"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ inputs.application-name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: yarn install --frozen-lockfile

      - name: Setup cargo cache
        id: cache-cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ./target
          key: cargo-${{ runner.os }}-${{ github.ref_name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-${{ github.ref_name }}-
            cargo-${{ runner.os }}-main-
            cargo-${{ runner.os }}-

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-${{ github.sha }}-${{ inputs.application-name }}
          path: ${{ inputs.working-directory }}/build

      - name: Deploy to Cloudflare (dry-run)
        if: inputs.dry-run == true
        run: yarn run deploy:prod --dry-run
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
